---
- name: Generate the npm directory path
  set_fact:
    _npm_dir: "\
      {{ _run_temp_dir.path }}/src\
      {% if item.npm_dir is defined %}\
      /{{ item.npm_dir }}\
      {% endif %}"

- name: Check if package.json exists
  stat:
    name: "{{ _npm_dir }}/package.json"
  register: _package_json

- name: Install NPM
  shell: "npm {{ item.npm_install_cmd | default('ci') }}"
  args:
    chdir: "{{ _npm_dir }}"
  when:
    - _package_json.stat.exists == true

- name: Run npm build
  shell: "npm run {{ item.npm_build_script_name | default('build') }}"
  args:
    chdir: "{{ _npm_dir }}"
  when:
    - _package_json.stat.exists == true

